name: Ubuntu

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: build
        run: mkdir build && cd build && cmake  .. --preset=debug && make -C debug

      - name: test
        run: |
          cmake -S ./tests -B ./build/debug/tests --preset=debug && make -C build/debug/tests && cd build/debug/tests && ctest --build-config Debug

      - name: install
        run: |
          cmake -S . -B ./build/release --preset=release && sudo make -C build/release install
          cmake -S ./tests -B ./build/release/tests --preset=release -DTEST_INSTALLED_VERSION=ON && make -C build/release/tests && cd build/release/tests && ctest --build-config Debug


