name: Windows

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install Ninja on Windows
        run: choco install ninja -y
      - name: Set up Visual Studio environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      - name: build
        run: |
          cmake -S . -B ./build/debug --preset=win-x64-debug
          cmake --build build --config Debug -j4
      - name: test
        run: |
          cmake -S tests -B ./build/debug/tests --preset=win-x64-debug
          ninja -C build/debug/tests
          build/debug/tests/cpptemplateTests
